codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      compiler:
        flags:
          - compiler
        target: 95%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files"
  require_changes: false
