import type { E2EScenarioInput } from "#type-declarations/testing"

import { defineE2ETestFile } from "../scenario-module"

const scenario: E2EScenarioInput = {
    input: `
        <lang-js>
            let options = reactive(["A", "B", "C"])
            let selected = reactive([])

            const addOption = () => {
                options = [...options, "D"]
            }

            const removeLastOption = () => {
                options = options.slice(0, -1)
            }
        </lang-js>

        <section data-page="form-handling-dynamic-choice-group">
            <h1 id="title">Dynamic Choice Group</h1>
            <button id="btn-add" @click={addOption}>Add option</button>
            <button id="btn-remove" @click={removeLastOption}>Remove last</button>

            <div id="group">
                <label #for={opt of options}>
                    <input type="checkbox" !value={opt} &group={selected} />
                    <span class="opt-label">{opt}</span>
                </label>
            </div>
            <p id="selected">Selected: {selected}</p>
        </section>
    `
}

export default await defineE2ETestFile(import.meta.url, scenario, ({ test, expect }) => {
    test("checkbox group generated by #for stays in sync with dynamic options", async ({
        page,
        visitScenario
    }) => {
        await visitScenario(scenario)
        await expect(page.locator("#group input[type=checkbox]")).toHaveCount(3)

        // 勾选 A → selected 更新
        // Check A → selected update
        await page.locator("#group input[value=A]").check()
        await expect(page.locator("#selected")).toHaveText("Selected: A")

        // 动态新增选项 → 新 checkbox 出现
        // Dynamically add option → new checkbox appears
        await page.locator("#btn-add").click()
        await expect(page.locator("#group input[type=checkbox]")).toHaveCount(4)
        await page.locator("#group input[value=D]").check()
        await expect(page.locator("#selected")).toHaveText("Selected: A,D")

        // 动态移除选项 → 对应 checkbox 消失
        // Dynamically remove option → corresponding checkbox disappears
        await page.locator("#btn-remove").click()
        await expect(page.locator("#group input[type=checkbox]")).toHaveCount(3)
        await expect(page.locator("#group input[value=D]")).toHaveCount(0)
    })
})
