import type { GeneralFunc } from "../../util/types"

export const commonMessage = (<T extends Record<string, [number, GeneralFunc]>>(obj: T): T => {
    return obj
})({
    InstantiateComponentManually: [
        2003,
        () => {
            return "You can not intantiate the component manually because this process requires some state generated by compiler."
        }
    ]
})
